In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel(r'C:\Users\candi\Downloads\coalpublic2013.xls', header=[3])
df

,Year,MSHA ID,Mine Name,Mine State,Mine County,Mine Status,Mine Type,Company Type,Operation Type,Operating Company,Operating Company Address,Union Code,Coal Supply Region,Production (short tons),Average Employees,Labor Hours
0,2013,103381,Tacoa Highwall Miner,Alabama,Bibb,"Active, men working, not producing",Surface,Indepedent Producer Operator,Mine only,"Jesse Creek Mining, Llc","1615 Kent Dairy Rd, Alabaster, AL 35007",,Appalachia Southern,56004,10,22392
1,2013,103404,Reid School Mine,Alabama,Blount,Permanently abandoned,Surface,Indepedent Producer Operator,Mine only,"Taft Coal Sales & Associates,","3000 Riverchase Galleria Ste 1, Birmingham, AL...",UNIT,Appalachia Southern,28807,18,28447
2,2013,100759,North River #1 Underground Min,Alabama,Fayette,"Active, men working, not producing",Underground,Indepedent Producer Operator,Mine and Preparation Plant,Jim Walter Resources Inc,"3114 County Rd 63 S, Berry, AL 35546",UNIT,Appalachia Southern,1440115,183,474784
3,2013,103246,Bear Creek,Alabama,Franklin,Active,Surface,Indepedent Producer Operator,Mine only,"Birmingham Coal & Coke Co., In","912 Edenton Street, Birmingham, AL 35242",,Appalachia Southern,87587,13,29193
4,2013,103451,Knight Mine,Alabama,Franklin,Active,Surface,Indepedent Producer Operator,Mine only,"Birmingham Coal & Coke Co., In","P.O. Box 354, Lynn, AL 35242",,Appalachia Southern,147499,27,46393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,2013,1103254,Fidelity Mine,Refuse Recovery,Perry,"Active, men working, not producing",Refuse,Operating Subsidiary,Mine and Preparation Plant,"Energy Recovery, Llc","P.O. Box 483, Benton, IL 62812",,Illinois Basin,18532,4,8249
1446,2013,1102636,Wfi,Refuse Recovery,Saline,"Active, men working, not producing",Refuse,Indepedent Producer Operator,Mine only,Wfi,"4270 North America Road, Galatia, IL 62935",,Illinois Basin,5070,4,1449
1447,2013,4407233,Gobco #8,Refuse Recovery,Russell,Active,Refuse,Indepedent Producer Operator,Mine only,Mountain Fuels Inc,"P.O. Box 749, Abingdon, VA 24210",,Appalachia Central,377607,16,43684
1448,2013,1518524,Turkey Pen Refuse,Refuse Recovery,Pike,Active,Refuse,Indepedent Producer Operator,Mine only,Belcher & Company Excavating I,"2340 Conaway Road, Big Rock, VA 24603",,Appalachia Central,7744,2,622
1449,2013,1519685,Fedscreek Refuse Pile,Refuse Recovery,Pike,"Active, men working, not producing",Refuse,Indepedent Producer Operator,Mine only,P B Dirt Movers Inc.,"P.O. Box 10, Big Rock, VA 24603",,Appalachia Central,17357,3,1020

In [2]:
df.get('Union Code')

0
1       UNIT
2       UNIT
3
4
        ...
1445
1446
1447
1448
1449
Name: Union Code, Length: 1450, dtype: object

In [3]:
df['Mine State']

0               Alabama
1               Alabama
2               Alabama
3               Alabama
4               Alabama
             ...
1445    Refuse Recovery
1446    Refuse Recovery
1447    Refuse Recovery
1448    Refuse Recovery
1449    Refuse Recovery
Name: Mine State, Length: 1450, dtype: object

In [4]:
df_ = df.astype(dtype={'Year': np.int32, 'Labor Hours': np.float32})
df_

,Year,MSHA ID,Mine Name,Mine State,Mine County,Mine Status,Mine Type,Company Type,Operation Type,Operating Company,Operating Company Address,Union Code,Coal Supply Region,Production (short tons),Average Employees,Labor Hours
0,2013,103381,Tacoa Highwall Miner,Alabama,Bibb,"Active, men working, not producing",Surface,Indepedent Producer Operator,Mine only,"Jesse Creek Mining, Llc","1615 Kent Dairy Rd, Alabaster, AL 35007",,Appalachia Southern,56004,10,22392.0
1,2013,103404,Reid School Mine,Alabama,Blount,Permanently abandoned,Surface,Indepedent Producer Operator,Mine only,"Taft Coal Sales & Associates,","3000 Riverchase Galleria Ste 1, Birmingham, AL...",UNIT,Appalachia Southern,28807,18,28447.0
2,2013,100759,North River #1 Underground Min,Alabama,Fayette,"Active, men working, not producing",Underground,Indepedent Producer Operator,Mine and Preparation Plant,Jim Walter Resources Inc,"3114 County Rd 63 S, Berry, AL 35546",UNIT,Appalachia Southern,1440115,183,474784.0
3,2013,103246,Bear Creek,Alabama,Franklin,Active,Surface,Indepedent Producer Operator,Mine only,"Birmingham Coal & Coke Co., In","912 Edenton Street, Birmingham, AL 35242",,Appalachia Southern,87587,13,29193.0
4,2013,103451,Knight Mine,Alabama,Franklin,Active,Surface,Indepedent Producer Operator,Mine only,"Birmingham Coal & Coke Co., In","P.O. Box 354, Lynn, AL 35242",,Appalachia Southern,147499,27,46393.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,2013,1103254,Fidelity Mine,Refuse Recovery,Perry,"Active, men working, not producing",Refuse,Operating Subsidiary,Mine and Preparation Plant,"Energy Recovery, Llc","P.O. Box 483, Benton, IL 62812",,Illinois Basin,18532,4,8249.0
1446,2013,1102636,Wfi,Refuse Recovery,Saline,"Active, men working, not producing",Refuse,Indepedent Producer Operator,Mine only,Wfi,"4270 North America Road, Galatia, IL 62935",,Illinois Basin,5070,4,1449.0
1447,2013,4407233,Gobco #8,Refuse Recovery,Russell,Active,Refuse,Indepedent Producer Operator,Mine only,Mountain Fuels Inc,"P.O. Box 749, Abingdon, VA 24210",,Appalachia Central,377607,16,43684.0
1448,2013,1518524,Turkey Pen Refuse,Refuse Recovery,Pike,Active,Refuse,Indepedent Producer Operator,Mine only,Belcher & Company Excavating I,"2340 Conaway Road, Big Rock, VA 24603",,Appalachia Central,7744,2,622.0
1449,2013,1519685,Fedscreek Refuse Pile,Refuse Recovery,Pike,"Active, men working, not producing",Refuse,Indepedent Producer Operator,Mine only,P B Dirt Movers Inc.,"P.O. Box 10, Big Rock, VA 24603",,Appalachia Central,17357,3,1020.0

NOT (~)
AND (&)
OR (|)
XOR (^)

In [5]:
Uni = df[(df['Production (short tons)'] >= 28000) & (df['Average Employees'] == 10 )]
Uni

,Year,MSHA ID,Mine Name,Mine State,Mine County,Mine Status,Mine Type,Company Type,Operation Type,Operating Company,Operating Company Address,Union Code,Coal Supply Region,Production (short tons),Average Employees,Labor Hours
0,2013,103381,Tacoa Highwall Miner,Alabama,Bibb,"Active, men working, not producing",Surface,Indepedent Producer Operator,Mine only,"Jesse Creek Mining, Llc","1615 Kent Dairy Rd, Alabaster, AL 35007",,Appalachia Southern,56004,10,22392
37,2013,103195,Mccollum/Sparks Branch Mine,Alabama,Walker,Active,Surface,Indepedent Producer Operator,Mine only,"Quality Coal, Inc.","17405 Hwy 69 S, Jasper, AL 35501",,Appalachia Southern,71910,10,17411
156,2013,1519608,No 2,Kentucky (East),Bell,Permanently abandoned,Surface,Indepedent Producer Operator,Mine only,Tackett Creek Mining Inc,"111 Mill Creek Rd, Pathfork, KY 40863",,Appalachia Central,50539,10,24442
401,2013,1518978,Buckeye Highwall Miner,Kentucky (East),Perry,Temporarily closed,Surface,Operating Subsidiary,Mine only,James River Coal Service Compa,"P.O. Box 189, Lackey, KY 41643",,Appalachia Central,164140,10,23502
478,2013,1519604,Beaver Mine No. 1,Kentucky (East),Pike,Active,Surface,Indepedent Producer Operator,Mine only,"Mill Branch Processing, Inc.","P.O. Box 100, Ashcamp, KY 41512",,Appalachia Central,48125,10,14113
518,2013,1800776,No. 1 Surface,Maryland,Allegany,Active,Surface,Indepedent Producer Operator,Mine only,"Walker Brothers Mining, Inc.","P.O. Box 583, Midlothian, MD 21543",,Appalachia Northern,40354,10,20183
590,2013,3401343,Phoenix No 3,Oklahoma,Craig,Permanently abandoned,Surface,Indepedent Producer Operator,Mine only,Phoenix Mining Company,"P.O. Box 475, Keota, OK 74941",,Interior,28441,10,21486
1025,2013,4407313,Maple Highwall,Virginia,Russell,Active,Surface,Indepedent Producer Operator,Mine only,"Omega Highwall Mining Ii, Llc","P.O. Box 428, Richlands, VA 24641",,Appalachia Central,89623,10,12246
1279,2013,4606089,Minway Surface,West Virginia (Southern),Mingo,"Active, men working, not producing",Surface,Indepedent Producer Operator,Mine only,Consol Of Kentucky Inc.,"P.O. Box 76, Naugatuck, WV 25685",,Appalachia Central,148943,10,23089
1317,2013,4607355,Bucy Job,West Virginia (Northern),Monongalia,Active,Surface,Indepedent Producer Operator,Mine only,Shafer Brothers Construction I,"668 Lower Hildebrand Rd, Morgantown, WV 26501",,Appalachia Northern,95428,10,13184

In [6]:
Uni2 = df[(df['Mine Type'] == 'Underground') & (df['Average Employees'] == 10 )]
Uni2

,Year,MSHA ID,Mine Name,Mine State,Mine County,Mine Status,Mine Type,Company Type,Operation Type,Operating Company,Operating Company Address,Union Code,Coal Supply Region,Production (short tons),Average Employees,Labor Hours
440,2013,1518436,Mine No. 1,Kentucky (East),Pike,Permanently abandoned,Underground,Indepedent Producer Operator,Mine only,Ranger Contracting,"P.O. Box 392, Pikeville, KY 41502",,Appalachia Central,18373,10,8559
554,2013,3304188,Kensington Prep. Plant,Ohio,Columbiana,"Active, men working, not producing",Underground,Indepedent Producer Operator,Preparation Plant,Rosebud Mining Company,"95 Lisbon St., Carrollton, OH 44615",,Appalachia Northern,0,10,20432
874,2013,3606330,Cleaning Plant,Pennsylvania (Bituminous),Somerset,Active,Underground,Indepedent Producer Operator,Preparation Plant,Wilson Creek Energy Llc,"609 Georgian Place, Somerset, PA 15501",,Appalachia Northern,0,10,18561
1226,2013,4607852,Big Creek Washer,West Virginia (Southern),Mcdowell,Active,Underground,Contractor,Preparation Plant,Baystar Coal Company Inc,"P.O. Box 1030, Bluefield, VA 24605",,Appalachia Central,0,10,22951
1233,2013,4608955,Mine No. 2,West Virginia (Southern),Mcdowell,Active,Underground,Indepedent Producer Operator,Mine only,"Resurrection Coal Company, Inc","P.O. Box 269, Jolo, WV 24850",,Appalachia Central,22544,10,19453
1316,2013,4606556,River Terminal,West Virginia (Northern),Monongalia,Active,Underground,Operating Subsidiary,Preparation Plant,Coresco Llc,"308 Dents Run Road, Morgantown, WV 26501",,Appalachia Northern,0,10,19499

In [7]:
df_sub=df[['MSHA ID', 'Labor Hours']].groupby('MSHA ID').sum()
df_sub

         Labor Hours
MSHA ID
100329        144002
100347        215295
100515          6240
100759        474784
100851       1001809
...              ...
4801353      2811138
4801429       161270
4801645        35687
4801646       661265
5000030       286079

[1321 rows x 1 columns]

In [8]:
df_sub_mean = df[['MSHA ID', 'Labor Hours']].groupby('MSHA ID').mean()
df_sub_mean

         Labor Hours
MSHA ID
100329      144002.0
100347      215295.0
100515        6240.0
100759      474784.0
100851     1001809.0
...              ...
4801353    2811138.0
4801429     161270.0
4801645      35687.0
4801646     661265.0
5000030     286079.0

[1321 rows x 1 columns]

In [9]:
df_sub - df_sub_mean

         Labor Hours
MSHA ID
100329           0.0
100347           0.0
100515           0.0
100759           0.0
100851           0.0
...              ...
4801353          0.0
4801429          0.0
4801645          0.0
4801646          0.0
5000030          0.0

[1321 rows x 1 columns]

https://realpython.com/pandas-dataframe/#applying-arithmetic-operations